services:
  function-runner:
    build: ./modules/function-runner/.
    environment:
      - VM_EXECUTION_TIMEOUT_MS=5000
      - MAX_WORKERS=8
      - MIN_WORKERS=1
      - MAX_TASKS_PER_WORKER=1
      - PORT=3000
      - FUNCTION_STORAGE_URL=http://function-storage:3000
    ports:
      - "3000:3000"
    depends_on:
      - function-storage
      - postgres
  function-storage:
    build: ./modules/function-storage/.
    environment:
      - PORT=3000
    ports:
      - "3001:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"