// Generated By AI - Comprehensive API Documentation
// This file contains developer-facing documentation schemas for the Game API.

import z from 'zod';
import { 
  PlayerAction, 
  MahjongGameRoundStatus, 
  LifecycleHookType, 
  DecisionHookType, 
  PlayerStatusPatches, 
  GameStatusPatches,
  PatchActionType,
  PluginActionType,
  StoragePatchType,
  type PluginManifest,
  type PluginHookCategory,
  type PluginHookMode,
  type MahjongTile,
  type ActionSharedData,
  type GameStatsPatch,
  type StoragePatch
} from 'utils';

/**
 * Global Storage Interface
 * Describes the shared state accessible by all plugins.
 */
export interface GlobalStorage {
  riichiStatus?: Record<string, boolean>;
  furitenStatus?: Record<string, boolean>;
  currentDoraCount?: number;
  [key: string]: any;
}

/**
 * Combined Storage Type
 * Plugins receive their private storage merged with Global Storage keys 
 * they have declared in `usedGlobalStorageKeys`.
 */
export type CombinedStorage<T> = T & GlobalStorage;

/**
 * Plugin Hook Context
 * Provided to every hook implementation.
 */
export interface PluginHookContext<T = any, P = any> {
  requestId: string;
  manifest: PluginManifest;
  hook: LifecycleHookType | DecisionHookType;
  category: PluginHookCategory;
  mode: PluginHookMode;
  storage: CombinedStorage<T>;
  payload: P;
  playerId?: string;
  roundIndex?: number;
}

/**
 * Evaluation Payload
 * The payload returned by onEvaluateHand within the `pluginAction` array.
 */
export interface EvaluationPayload {
  yaku: string;
  han: number;
  fu?: number;
  isYakuman?: boolean;
}

/**
 * Plugin Hook Result
 */
export interface PluginHookResult<T = any> {
  pluginStorage?: T;
  storagePatch?: StoragePatch<T>[];
  gameStatsPatch?: GameStatsPatch[];
  pluginAction?: any[];
  stopPropagation?: boolean;
  reject?: boolean;
}

/**
 * --- Zod Schemas for Runtime Validation ---
 */

export const MahjongTileSchema = z.object({
  type: z.number(),
  index: z.number(),
});

export const EvaluationPayloadSchema = z.object({
  yaku: z.string(),
  han: z.number(),
  fu: z.number().optional(),
  isYakuman: z.boolean().optional(),
});

export const PluginActionDefinitionSchema = z.object({
  id: z.string().optional(),
  label: z.string().optional(),
  type: z.nativeEnum(PluginActionType),
  payload: z.union([EvaluationPayloadSchema, z.record(z.string(), z.any())]).optional(),
});

export const StoragePatchSchema = z.object({
  type: z.nativeEnum(StoragePatchType),
  key: z.string(),
  value: z.any(),
});

export const PluginHookResultSchema = z.object({
  reject: z.boolean().optional(),
  stopPropagation: z.boolean().optional(),
  pluginAction: z.array(z.union([z.number(), PluginActionDefinitionSchema])).optional(),
  gameStatsPatch: z.array(z.any()).optional(),
  storagePatch: z.array(StoragePatchSchema).optional(),
});

/**
 * Game.next API Schemas
 */
export const GameNextRequestSchema = z.object({
  requestId: z.string(),
  args: z.object({
    action: z.nativeEnum(PlayerAction),
    playerId: z.string(),
  }).optional(),
});
