FROM oven/bun AS builder
WORKDIR /app
COPY modules/function-runner /app/modules/function-runner
COPY package.json bun.lock ./
COPY modules/proto /app/modules/proto
COPY modules/utils /app/modules/utils
RUN bun install
RUN bun run proto:generate
WORKDIR /app/modules/function-runner
#RUN if grep -q '"generate"' package.json 2>/dev/null; then bun run generate || true; fi
FROM oven/bun
WORKDIR /app
# copy installed dependencies and source from builder
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/modules/function-runner ./modules/function-runner
COPY --from=builder /app/modules/utils ./modules/utils
COPY --from=builder /app/modules/proto ./modules/proto
WORKDIR /app/modules/function-runner
EXPOSE 4001
CMD ["bun", "run", "index.ts"]
