// Generated By AI
// This file contains developer-facing documentation schemas for the Game API.
// It exposes zod schemas that can be used for runtime validation and TS types
// derived from those schemas. Keep these schemas in sync with the `utils`
// package types when possible.

import z from 'zod';
import { PlayerAction, type MahjongTile } from 'utils';

/**
 * NOTE on MahjongTile: replace MahjongTileSchema with a concrete zod schema
 * matching your project's MahjongTile shape when that schema is available.
 */
export const MahjongTileSchema = z.any();

/**
 * ResolvePlayerActionArgsDocSchema
 * - `action`: enum describing the action (DrawTile/Chi/Pon/Kan/Ron/Tsumo/Riichi)
 * - `playerId`: id of the acting player
 * - `tiles`: optional snapshot of player's tiles for plugin evaluation
 * - `payload`: optional plugin-specific additional metadata
 */
export const ResolvePlayerActionArgsDocSchema = z.object({
  action: z.nativeEnum(PlayerAction),
  playerId: z.string(),
  tiles: z.array(MahjongTileSchema).optional(),
  payload: z.record(z.string(), z.unknown()).optional(),
});

export type ResolvePlayerActionArgsDoc = z.infer<
  typeof ResolvePlayerActionArgsDocSchema
>;

/**
 * Game.next request/response schemas
 */
export const GameNextRequestDocSchema = z.object({
  requestId: z.string(),
  args: ResolvePlayerActionArgsDocSchema.optional().nullable(),
});

export type GameNextRequestDoc = z.infer<typeof GameNextRequestDocSchema>;

export const GameNextResponseDocSchema = z.object({
  requestId: z.string(),
});

export type GameNextResponseDoc = z.infer<typeof GameNextResponseDocSchema>;

/**
 * Plugin Hook Payloads
 * - Hooks are lifecycle events invoked by the engine (e.g., RoundStart, PlayerAction)
 * - Each hook can define a specific payload shape. For documentation we provide
 *   a generic payload schema and example helper schemas for common cases.
 */
export const PluginHookPayloadSchema = z.object({
  roundIndex: z.number().optional(),
  requestId: z.string().optional(),
  playerId: z.string().optional(),
  event: z.record(z.string(), z.unknown()).optional(),
  tiles: z.array(MahjongTileSchema).optional(),
});

export type PluginHookPayload = z.infer<typeof PluginHookPayloadSchema>;

/**
 * Plugin Hook Result Item
 * - The engine expects plugin hooks to return an array of result items.
 * - Each item may include:
 *   - `reject`: boolean to cancel/deny the current hook processing
 *   - `pluginAction`: an action description the engine may execute (shape is
 *     intentionally permissive here; adapt to your concrete action schema)
 *   - `gameStatsPatch`: array of patch objects to apply to game state
 *
 * The engine will validate each returned item against this schema and ignore
 * invalid items. Use `parsePluginHookResult` for a safe parse helper.
 */
export const PluginHookResultItemSchema = z.object({
  reject: z.boolean().optional(),
  pluginAction: z.array(z.number()).optional(),
  gameStatsPatch: z.array(z.unknown()).optional(),
});

export const PluginHookResultSchema = z.array(PluginHookResultItemSchema);

export type PluginHookResultItem = z.infer<typeof PluginHookResultItemSchema>;
export type PluginHookResult = z.infer<typeof PluginHookResultSchema>;

/**
 * Safe parse helper for plugin hook results
 */
export function parsePluginHookResult(
  raw: unknown,
):
  | { success: true; data: PluginHookResult }
  | { success: false; error: z.ZodError } {
  const parsed = PluginHookResultSchema.safeParse(raw);
  if (parsed.success) return { success: true, data: parsed.data };
  return { success: false, error: parsed.error };
}

/**
 * Developer-facing example payloads (not used at runtime)
 */
export const GameApiDocs = {
  exampleResolveAction(): ResolvePlayerActionArgsDoc {
    return {
      action: PlayerAction.DrawTile,
      playerId: 'player-uuid-1',
      tiles: [],
      payload: { index: 0 },
    };
  },
};
