FROM oven/bun AS builder
WORKDIR /app
COPY . .
RUN bun install --frozen-lockfile
RUN bun build index.ts --compile --outfile function-storage

FROM busybox
WORKDIR /app
COPY --from=builder /app/function-storage .
RUN chmod +x function-storage
EXPOSE 3000
CMD ["./function-storage"]